USE_QPU: true
ANNEALING_TIME: 1
NUM_READS: 256
NUM_SWEEPS: 200

IMAGE_SIZE: 32
DATASET_SIZE: null  # full MNIST is 60_000
BATCH_SIZE: 128
RANDOM_SEED: 775321899904
LOSS_FUNCTION: mmd
N_REPLICAS: 8
LATENT_TO_DISCRETE: null  # test heaviside
INITIAL_PREFACTOR: 1.0
MAX_DEQUE_SIZE: 4096
ITERATIONS_BEFORE_RESAMPLING: 100

# autoencoder parameters
AUTOENCODER_INITIAL_LR: 0.0001
AUTOENCODER_FINAL_LR: 0.00001
AUTOENCODER_WEIGHT_DECAY: 0.01

# boltzmann machine parameters
BM_INITIAL_LR: 0.001
BM_FINAL_LR: 0.0001
BM_WEIGHT_DECAY: 0.01
MEASURE_PREFACTOR: true

WINDOW_LENGTH: 10
